#!/usr/bin/env bash

if [ "$1" == "setup" ]; then
    set -eux
    if ! command -v uv >/dev/null 2>&1; then
        pip install uv
    fi
    uv sync --all-extras
    uv run pre-commit install
elif [ "$1" == "compile" ]; then
    uv lock
elif [ "$1" == "sync" ]; then
    uv sync --all-extras
elif [ "$1" == "test" ]; then
    uv run pytest "${@:2}"
elif [ "$1" == "build-macos" ]; then
    pushd backend
    GOOS=darwin GOARCH=arm64 go build -buildmode=c-shared -o ./whatsmeow/whatsmeow-darwin-arm64.dylib main.go
    GOOS=darwin GOARCH=amd64 go build -buildmode=c-shared -o ./whatsmeow/whatsmeow-darwin-amd64.dylib main.go
    popd
elif [ "$1" == "test-setup" ]; then
    rm -rf build dist *.egg-info
    uv run python -m setuptools.dist check
    uv build && echo ok
elif [ "$1" == "format" ]; then
    uv run black .
elif [ "$1" == "lint" ]; then
    uv run ruff check .
    uv run ruff format .
    uv run mypy .
elif [ "$1" == "cleanup" ]; then 
    rm -rf build dist *.egg-info whatsfly/last_binary_update.txt whatsfly/__pycache__ whatsfly/*/__pycache__ .venv
elif [ "$1" == "bump" ]; then
    pushd backend 
    go get -u
    go mod tidy
    popd
    $0 compile
    $0 sync
    $0 setup
    $0 lint
    $0 format
    $0 test-setup
    $0 cleanup
else
    echo "Unrecognized command: $1"
fi
