name: Build docs

on:
  push:
    branches: ["main"]
    paths: [".github/**", "docs/**", "whatsfly/whatsapp.py" ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v6.0.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: ">3.12"
        # File containing the Python version to use. Example: .python-version
        
        # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
        cache: pip # optional
        # The target architecture (x86, x64, arm64) of the Python or PyPy interpreter.
    
        # Set this option if you want the action to check for the latest available version that satisfies the version spec.
        check-latest: true # optional
        # The token used to authenticate when fetching Python distributions from https://github.com/actions/python-versions. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
        
    - name: Install library
      run: pip install whatsfly_Labfox mkdocs mkdocstrings mkdocstrings-python mike mkdocs-material 

    - name: Build docs
      run: |
        cd docs
        python3 -m mkdocs build

    - name: Upload docs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: docs/site/
    
  deploy:
    # Add a dependency to the build job
    needs: build-docs

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        with:
          artifact_name: site
